#!/bin/bash
# Default entrypoint for SMC containers
cd /home/user

upload_results() {
    # It's up to you to write results_upload_script to upload whatever results you want
    echo "upload_results"
    if [ -f results_upload_script ]; then
        echo "upload_results see /home/user/results_upload_script"
        su user -c "bash --login results_upload_script"
    fi
}

need_restart=1
while [ ! -f /tmp/shutdown-container ]
do
    while [ "$SMC_MULTI_NODE" -eq 1 ]; do
        su user -c "sleep 1" || exit 1
        if [ -f /home/user/smc_multinode_setup ]; then
            su user -c /home/user/smc_multinode_setup || need_restart=1
            break
        else
            continue
        fi
    done
    if [ "$SMC_ZIP_FILESECRET" != "" ] && hostname | grep -q '\-00$'; then
        # Without code.zip it's up to you to upload and run your code
        if [ ! -f code.7z ]; then
            su user -c "wget -q -O code.7z https://www.smallcloud.ai/v1/task-file-download?fn=${SMC_ZIP_FILESECRET}"
        fi
    fi
    if [ "$SMC_PKL_FILESECRET" != "" ] && [ "$need_restart" -eq 1 ]; then
        # On all nodes, not just 00
        killall -s SIGUSR1 python
        countdown=60
        while [ -n "$(pidof python)" ]; do
            sleep 1
            countdown=$((countdown - 1))
            if [ $countdown -eq 0 ]; then
                killall -9 python
                break
            fi
        done
    fi
    if [ "$SMC_PKL_FILESECRET" != "" ] && [ "$need_restart" -eq 1 ] && [ -f smc_run_task.py ] && hostname | grep -q '\-00$'; then
        # Only on node 00
        need_restart=0
        su user -c "wget -q -O pickled-function-call.pkl https://www.smallcloud.ai/v1/task-file-download?fn=${SMC_PKL_FILESECRET}"
        su user -c 'bash --login -c "python smc_unpack_code.py"'
        if [ -f smc_multinode_setup ]; then
            su user -c 'bash --login -c "nohup 2>&1 mpirun -prepend-rank -f mpihosts python smc_run_task.py | tee --append ~/output.log &"'
        else
            su user -c 'bash --login -c "nohup 2>&1 mpirun -prepend-rank -n $SMC_GPUS python smc_run_task.py | tee --append ~/output.log &"'
        fi
    fi
    su user -c "sleep 60" || break    # sleep is killable by user, the container will exit
    upload_results
done

# final upload before exiting the container
upload_results
