#!/bin/bash
rm /etc/update-motd.d/10-help-text
rm /etc/update-motd.d/50-motd-news
rm /etc/update-motd.d/85-fwupd
rm /etc/update-motd.d/88-esm-announce
rm /etc/update-motd.d/90-updates-available
rm /etc/update-motd.d/91-contract-ua-esm-status
rm /etc/update-motd.d/91-release-upgrade
rm /etc/update-motd.d/95-hwe-eol
rm /etc/update-motd.d/98-fsck-at-reboot
rm /etc/update-motd.d/98-reboot-required
