#!/bin/bash
set -xe
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    rsyslog \
    mc \
    rsync \
    inetutils-ping \
    net-tools \
    psmisc \
    telnet \
    vim \
    p7zip \
    python3 \
    python3-pip \
    mpich \
    libmpich-dev \
    libaio-dev \
    strace \
    clang-11 \
    lldb-11 \
    lld-11 \
    clangd-11
apt-get purge -y --auto-remove unattended-upgrades
systemctl disable apt-daily-upgrade.timer
systemctl mask apt-daily-upgrade.service
systemctl disable apt-daily.timer
systemctl mask apt-daily.service
