#!/bin/bash
# wget https://developer.download.nvidia.com/compute/cuda/11.4.2/local_installers/cuda_11.4.2_470.57.02_linux.run
# bash cuda_11.4.2_470.57.02_linux.run
curl -sLo miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py38_4.8.3-Linux-x86_64.sh
chmod +x miniconda.sh
./miniconda.sh -b -p /usr/local/miniconda
rm miniconda.sh
