#!/bin/bash
set -xe
echo "export PATH=/usr/local/miniconda/bin:/usr/local/cuda/bin:~/.local/bin:\$PATH" > /etc/profile.d/50-smc.sh
apt-get clean

echo "[Unit]
Description=Mount Encrypted Home

[Service]
ExecStart=/root/smc-os-scripts/bits-and-pieces/mount-encrypted-home.sh

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/mount-encrypted-home.service

echo "[Unit]
Description=Unpack and Run Code

[Service]
ExecStart=/root/smc-os-scripts/bits-and-pieces/unpack-and-run.sh

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/unpack-and-run.service

#sed -i 's/After=network.target auditd.service/After=network.target auditd.service mount-encrypted-home.service/' /etc/systemd/system/sshd.service
systemctl daemon-reload
systemctl enable mount-encrypted-home.service
systemctl enable unpack-and-run.service

# Before giving a VM to you, SMC hypervisor will:
# 1. Mount / on hypervisor
# 2. Run ssh-keygen to generate new host identity, send fingerprint to you to put into known_hosts.
# 3. Set hostname the same as your task name.
# 4. Set a static IP address.
# 5. Forbid password authentication.
# 6. Write a welcome message to update-motd.d/
# 7. Install or not an agent depending on the task settings (see web UI).
# 8. Unmount /
# 9. Start VM.
