#!/bin/sh
set -xe
echo "export PATH=/usr/local/miniconda/bin:\$PATH" > /etc/profile.d/50-smc.sh

echo "[Unit]
Description=Mount Encrypted Home

[Service]
ExecStart=/root/smc-os-scripts/bits-and-pieces/mount-encrypted-home.sh

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/mount-encrypted-home.service
systemctl daemon-reload
systemctl enable mount-encrypted-home.service

# Before giving VM to you, SMC hypervisor will:
# 1. Mount /
# 2. Run ssh-keygen to generate new host identity, send fingerprint to you to put into known_hosts.
# 3. Set hostname the same as your task name.
# 4. Set a static IP address.
# 5. Forbid password authentication.
# 6. Write a welcome message to update-motd.d/
# 7. Unmount /
# 8. Start VM.
